Modules/Blog/Routes/backend.php
<?php

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'blog'], function () {
    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
});

Modules/Blog/Routes/web.php
<?php

use Modules\Blog\Http\Controllers\Frontend\ProposeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('blog')->as('blog.')->group(function() {
    Route::get('/', 'BlogController@index')->name('index');
    Route::get('/category/{slug}', 'BlogController@category')->name('category');
    Route::get('/{slug}', 'BlogController@post')->name('post');
});

Route::prefix('publishing')->as('publishing.')->group(function () {
    Route::get('/propose', [ProposeController::class, 'propose'])->name('propose');
    Route::get('/propose/{id}', [ProposeController::class, 'edit'])->name('edit');
    Route::post('/propose', [ProposeController::class, 'store'])->name('store');
    Route::put('/propose/{id}', [ProposeController::class, 'update'])->name('update');
    Route::delete('/propose/{id}', [ProposeController::class, 'destroy'])->name('destroy');
});

Modules/Blog/Entities/Post.php
<?php

namespace Modules\Blog\Entities;

use App\Traits\Mediatable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Modules\Forum\Entities\Traits\RecordsActivity;
use Modules\User\Entities\User;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;

class Post extends Model implements Searchable
{
    use RecordsActivity, Mediatable;

    const STATUS_PUBLISHED = 'PUBLISHED';
    const STATUS_DRAFT = 'DRAFT';
    const STATUS_PENDING = 'PENDING';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = ['category', 'creator', 'propose'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'featured' => 'boolean',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'published_at'
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'status_classname',
    ];

    /**
     * Spatie Searcheblable type.
     *
     * @var string
     */
    public string $searchableType = 'Articles';

    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();

        static::created(function ($post) {
            $post->update(['slug' => $post->title]);
        });
    }

    /**
     * Select all publish post
     *
     * @param  Builder  $builder
     * @return Builder
     */
    public function scopePublish(Builder $builder)
    {
        return $builder
            ->where('status', self::STATUS_PUBLISHED)
            ->whereDate('published_at', '<=', now());
    }

    /**
     * Set the proper slug attribute.
     *
     * @param string $value
     */
    public function setSlugAttribute($value)
    {
        if (static::where('slug', $slug = str_slug($value))->exists()) {
            $slug = "{$slug}-{$this->id}";
        }

        $this->attributes['slug'] = $slug;
    }

    /**
     * Return The post resume.
     *
     * @param  string  $value
     * @return string
     */
    public function getSummaryAttribute($value)
    {
        return str_limit(strip_tags($this->body), 150);
    }

    /**
     * @param  string  $value
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getImageAttribute($value)
    {
        if ($value) {
            return url('storage/' . $value);
        }

        if ($this->previewImage && !$value) {
            return $this->preview_image_link;
        }

        return null;
    }

    /**
     * Return the current format of status.
     *
     * @return string
     */
    public function getStatus()
    {
        switch ($this->status) {
            case self::STATUS_DRAFT:
                return 'Brouillon';
            case self::STATUS_PENDING:
                return 'En Attente';
            case self::STATUS_PUBLISHED:
                return 'Publié';
        }
    }

    /**
     * Return the current classname of status.
     *
     * @return string
     */
    public function getStatusClassnameAttribute()
    {
        switch ($this->status) {
            case self::STATUS_DRAFT:
                return 'bg-blue-100 text-blue-800';
            case self::STATUS_PENDING:
                return 'bg-orange-100 text-orange-800';
            case self::STATUS_PUBLISHED:
                return 'bg-green-100 text-green-800';
        }
    }

    /**
     * Return Category of the current post.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Return the Post author.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Return the post propose author.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function propose()
    {
        return $this->belongsTo(User::class, 'proposed_by');
    }

    /**
     * Return search result for post.
     *
     * @return SearchResult
     */
    public function getSearchResult(): SearchResult
    {
        $url = route('blog.post', ['slug' => $this->slug]);

        return new SearchResult(
            $this,
            $this->title,
            $url
        );
    }
}

Modules/Blog/Http/Controllers/Backend/PostController.php
<?php

namespace Modules\Blog\Http\Controllers\Backend;

use App\Repositories\MediaRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Blog\Entities\Category;
use Modules\Blog\Entities\Post;
use Modules\Blog\Http\Requests\PostRequest;
use Modules\Blog\Repositories\PostRepository;

class PostController extends Controller
{
    /**
     * @var PostRepository
     */
    protected PostRepository $repository;

    /**
     * @var MediaRepository
     */
    protected MediaRepository $mediaRepository;

    /**
     * PostController constructor.
     *
     * @param  PostRepository  $repository
     * @param  MediaRepository  $mediaRepository
     */
    public function __construct(PostRepository $repository, MediaRepository $mediaRepository)
    {
        $this->repository = $repository;
        $this->mediaRepository = $mediaRepository;
    }

    /**
     * Display resources list.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('blog::posts.index');
    }

    /**
     * Return form view to create a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        $status = collect([
            ['value' => Post::STATUS_DRAFT, 'name' => 'Brouillon'],
            ['value' => Post::STATUS_PUBLISHED, 'name' => 'Publié']
        ])->pluck('name', 'value');

        return view('blog::posts.create', compact('categories', 'status'));
    }

    /**
     * Create a new post to the database.
     *
     * @param  PostRequest $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function store(PostRequest $request)
    {
        $published_at = now();

        if ($request->input('date')) {
            $published_at = Carbon::createFromFormat('Y-m-d H:i', $request->input('date').' '.($request->input('time') ?? now()->format('H:i')))->toDateTimeString();
        }

        $post = $this->repository->create([
           'title' => $request->input('title'),
           'body' => $request->input('body'),
           'status' => $request->input('status'),
           'user_id' => auth()->id(),
           'category_id' => $request->input('category_id'),
           'published_at' => $published_at,
        ]);

        if ($request->input('media_id') !== "0") {
            $media = $this->mediaRepository->getById($request->input('media_id'));
            $media->update([
                'mediatable_type'   => $this->repository->model(),
                'mediatable_id'     => $post->id
            ]);
        }

        smilify('success', "L'article a été enregistré avec succès");

        return redirect()->route('admin.posts.index');
    }

    /**
     * Affiche la page d'edition de l'article.
     *
     * @param  Post  $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Post $post)
    {
        $categories = Category::pluck('name', 'id');
        $status = collect([
            ['value' => Post::STATUS_DRAFT, 'name' => 'Brouillon'],
            ['value' => Post::STATUS_PUBLISHED, 'name' => 'Publié']
        ])->pluck('name', 'value');

        return view('blog::posts.edit', compact('categories', 'status', 'post'));
    }

    /**
     * Mise a jour d'un article.
     *
     * @param  PostRequest  $request
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(PostRequest $request, $id)
    {
        $published_at = now();

        if ($request->input('date')) {
            $published_at = Carbon::createFromFormat('Y-m-d H:i', $request->input('date').' '.($request->input('time') ?? now()->format('H:i')))->toDateTimeString();
        }

        $post = $this->repository->updateById($id, [
            'title' => $request->input('title'),
            'body' => $request->input('body'),
            'status' => $request->input('status'),
            'user_id' => auth()->id(),
            'category_id' => $request->input('category_id'),
            'published_at' => $published_at,
        ]);

        if ($request->input('media_id') !== "0") {

            // Get the current Media
            $media = $this->mediaRepository->getById($request->input('media_id'));

            if ($post->previewImage && $post->previewImage->id !== (int) $request->input('media_id')) {
                // Remove media from the given collection
                $post->previewImage()->delete();

                $media->update([
                    'mediatable_type'   => $this->repository->model(),
                    'mediatable_id'     => $post->id,
                ]);
            }

            $media->update([
                'mediatable_type'   => $this->repository->model(),
                'mediatable_id'     => $post->id,
            ]);
        }

        smilify('success', "L'article a été modifié avec succès!");

        return redirect()->route('admin.posts.index');
    }

    /**
     * Supprimer un article de la base de données.
     *
     * @param  Request  $request
     * @param  Post  $post
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Request $request, Post $post)
    {
        try {
            $post->delete();

            smilify('success', "L'article a été supprimé avec succès");

            if ($request->isXmlHttpRequest()) {
                return response()->json(['redirect_url' => route('admin.posts.index')]);
            }

            return redirect()->route('admin.posts.index');
        } catch (\Exception $e) {
            smilify('error', "Vous ne pouvez pas supprimer cet article!");

            return back();
        }
    }
}

Modules/Blog/Resources/views/posts/create.blade.php
@extends('layouts.master')
@section('title', "Créer un nouvel article")

@section('content')

    @component('components.breadcrumb')
        <a href="{{ route('admin.posts.index') }}" class="text-gray-500 hover:text-gray-700 focus:outline-none focus:underline transition duration-150 ease-in-out">Tous les articles</a>
    @endcomponent

    <div class="mt-2 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
                {{ __('Créer un article') }}
            </h2>
        </div>
    </div>

    <div class="py-8">
        {!! Form::open(['route' => 'admin.posts.store', 'files' => true]) !!}
            <div class="flex flex-col lg:flex-row">
                <div class="w-full lg:w-2/3 space-y-5">
                    <div class="bg-white shadow rounded-md overflow-hidden px-4 py-4 sm:px-6">
                        <div class="grid grid-cols-2 gap-4">
                            <div class="col-span-2">
                                <label for="title" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Titre') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('title', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'title',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. Nouveautés de Laravel 7"
                                        ])
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="category_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Categorie') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('category_id', $categories, null, ['class' => 'form-select block w-full', 'id' => 'category_id']); !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Status') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('status', $status, null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'status'
                                        ]);
                                    !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white shadow rounded-md overflow-hidden p-4">
                        <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __("Contenu de l'article") }}</label>
                        <div id="editor" class="mt-2"></div>
                    </div>
                </div>
                <div class="w-full lg:w-1/3 space-y-5 mt-4 lg:mt-0 lg:ml-4">
                    <div class="shadow rounded-md">
                        <div class="bg-white p-4">
                            <h4 class="text-gray-500 font-medium text-base">{{ __('Date de publication') }}</h4>
                            <p class="text-gray-400 text-sm mt-2">{{ __('Spécifiez la date de publication de l\'article. Si aucune date n\'est renseigné la date du jour sera prise.') }}</p>
                        </div>
                        @include('components.datetime-picker', ['show' => false, 'publishedAt' => null])
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Article Preview') }}</h4>
                        <div id="dropzone-simple"></div>
                    </div>
                </div>
            </div>
            <div class="mt-8 border-t pt-5 border-gray-200">
                <div class="flex justify-end">
                    <button type="submit" class="btn btn-primary">{{ __('Enrégistrer') }}</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

Modules/Blog/Resources/views/posts/edit.blade.php
@extends('layouts.master')
@section('title', $post->title)

@section('content')

    @component('components.breadcrumb')
        <a href="{{ route('admin.posts.index') }}" class="text-gray-500 hover:text-gray-700 focus:outline-none focus:underline transition duration-150 ease-in-out">Tous les articles</a>
    @endcomponent

    <div class="mt-2 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-9 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
                {{ $post->title }}
            </h2>
        </div>
    </div>

    <div class="py-8">
        {!! Form::model($post, ['route' => ['admin.posts.update', $post], 'files' => true, 'method' => 'PUT']) !!}
            <div class="grid lg:grid-cols-6 lg:gap-8">
                <div class="col-span-6 lg:col-span-4 space-y-5">
                    <div class="bg-white shadow rounded-md overflow-hidden px-4 py-4 sm:px-6">
                        <div class="grid grid-cols-2 gap-4">
                            <div class="col-span-2">
                                <label for="title" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Titre') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('title', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'title',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. Nouveautés de Laravel 7"
                                        ])
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="category_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Categorie') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('category_id', $categories, null, ['class' => 'form-select block w-full', 'id' => 'category_id']); !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Status') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('status', $status, null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'status'
                                        ]);
                                    !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white shadow rounded-md overflow-hidden p-4">
                        <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __("Contenu de l'article") }}</label>
                        <div id="editor" class="mt-2" data-content="{{ $post->body }}"></div>
                    </div>
                </div>
                <div class="col-span-6 lg:col-span-2 space-y-5 mt-4 lg:mt-0">
                    <div class="shadow rounded-md">
                        <div class="bg-white p-4">
                            <h4 class="text-gray-500 font-medium text-base">{{ __('Date de publication') }}</h4>
                            <p class="text-gray-400 text-sm mt-2">{{ __('Spécifiez la date de publication de l\'article. Si aucune date n\'est renseigné la date du jour sera prise.') }}</p>
                        </div>
                        @include('components.datetime-picker', ['show' => true, 'publishedAt' => $post->published_at])
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Article Preview') }}</h4>
                        <div id="dropzone-simple" data-preview="{{ $post->preview_image_link }}" data-id="{{ $post->preview_image_id }}"></div>
                    </div>
                </div>
            </div>
            <div class="mt-8 border-t pt-5 border-gray-200">
                <div class="flex justify-end">
                    <button type="submit" class="btn btn-primary">{{ __('Enrégistrer') }}</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

Modules/Blog/Resources/views/posts/index.blade.php
@extends('layouts.master')
@section('title', "Listing des articles")

@section('content')

    <div class="md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">{{ __('Articles') }}</h2>
        </div>
        <div class="mt-4 flex md:mt-0 md:ml-4">
            <span class="shadow-sm rounded-md">
              <a href="{{ route('admin.posts.create') }}" class="btn btn-primary inline-flex items-center transition duration-150 ease-in-out">
                {{ __('Ajouter un article') }}
              </a>
            </span>
        </div>
    </div>

    @livewire('post-list')

@endsection