Modules/Tutorial/Routes/backend.php
<?php

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::resource('tutorials', 'TutorialController');

Modules/Tutorial/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/tutorials', 'TutorialController@index');
Route::get('/tutorial/category/{category}', 'TutorialController@category');
Route::get('/tutorial/{slug}', 'TutorialController@show')->name('tutorials.show');

Modules/Tutorial/Entities/Tutorial.php
<?php

namespace Modules\Tutorial\Entities;

use Alaouy\Youtube\Facades\Youtube;
use App\Traits\Mediatable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Modules\Forum\Entities\Traits\RecordsActivity;
use Modules\User\Entities\User;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;

class Tutorial extends Model implements Searchable
{
    use RecordsActivity, Mediatable;

    const STATUS_PUBLISHED = 'PUBLISHED';
    const STATUS_DRAFT = 'DRAFT';
    const STATUS_PENDING = 'PENDING';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'tutorial_tutorials';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = ['category', 'user'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'featured' => 'boolean',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'published_at'
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'status_classname',
        'preview_image_link',
    ];

    /**
     * Spatie Searcheblable type.
     *
     * @var string
     */
    public string $searchableType = 'Tutoriels';

    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();

        static::created(function ($post) {
            $post->update(['slug' => $post->title]);
        });
    }

    /**
     * Select all publish tutorial.
     *
     * @param  Builder  $builder
     * @return Builder
     */
    public function scopePublish(Builder $builder)
    {
        return $builder
            ->where('status', self::STATUS_PUBLISHED)
            ->whereDate('published_at', '<=', now());
    }

    /**
     * Set the proper slug attribute.
     *
     * @param string $value
     */
    public function setSlugAttribute($value)
    {
        if (static::where('slug', $slug = str_slug($value))->exists()) {
            $slug = "{$slug}-{$this->id}";
        }

        $this->attributes['slug'] = $slug;
    }

    /**
     * @param  string  $value
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function getImageAttribute($value)
    {
        if ($value) {
            return url('storage/'. $value);
        }

        if ($this->previewImage && !$value) {
            return $this->preview_image_link;
        }

        try {
            $video = Youtube::getVideoInfo($this->provider_id);

            if ($video) {
                return $video->snippet->thumbnails->medium->url;
            }
        } catch (\Exception $exception) {
            return null;
        }

        return null;
    }

    /**
     * Return the current format of status.
     *
     * @return string
     */
    public function getStatus()
    {
        switch ($this->status) {
            case self::STATUS_DRAFT:
                return 'Brouillon';
            case self::STATUS_PENDING:
                return 'En Attente';
            case self::STATUS_PUBLISHED:
                return 'Publié';
        }
    }

    /**
     * Return the current classname of status.
     *
     * @return string
     */
    public function getStatusClassnameAttribute()
    {
        switch ($this->status) {
            case self::STATUS_DRAFT:
                return 'bg-blue-100 text-blue-800';
            case self::STATUS_PENDING:
                return 'bg-orange-100 text-orange-800';
            case self::STATUS_PUBLISHED:
                return 'bg-green-100 text-green-800';
        }
    }

    /**
     * Retourne la categorie d'un tutoriel.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * Return the Tutorial author.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Return search result for post.
     *
     * @return SearchResult
     */
    public function getSearchResult(): SearchResult
    {
        $url = route('tutorials.show', ['slug' => $this->slug]);

        return new SearchResult(
            $this,
            $this->title,
            $url
        );
    }
}

Modules/Tutorial/Http/Controllers/Backend/TutorialController.php
<?php

namespace Modules\Tutorial\Http\Controllers\Backend;

use App\Repositories\MediaRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Tutorial\Entities\Category;
use Modules\Tutorial\Entities\Tutorial;
use Modules\Tutorial\Http\Requests\TutorialRequest;
use Modules\Tutorial\Repositories\TutorialRepository;

class TutorialController extends Controller
{
    /**
     * @var TutorialRepository
     */
    protected TutorialRepository $repository;

    /**
     * @var MediaRepository
     */
    protected MediaRepository $mediaRepository;

    /**
     * TutorialController new instance.
     *
     * @param  TutorialRepository  $repository
     * @param  MediaRepository  $mediaRepository
     */
    public function __construct(TutorialRepository $repository, MediaRepository $mediaRepository)
    {
        $this->repository = $repository;
        $this->mediaRepository = $mediaRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('tutorial::tutorials.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        $status = collect([
            ['value' => Tutorial::STATUS_DRAFT, 'name' => 'Brouillon'],
            ['value' => Tutorial::STATUS_PUBLISHED, 'name' => 'Publié']
        ])->pluck('name', 'value');

        return view('tutorial::tutorials.create', compact('categories', 'status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  TutorialRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TutorialRequest $request)
    {
        $published_at = now();

        if ($request->input('date')) {
            $published_at = Carbon::createFromFormat('Y-m-d H:i', $request->input('date').' '.($request->input('time') ?? now()->format('H:i')))->toDateTimeString();
        }

        $tutorial = $this->repository->create([
            'title' => $request->input('title'),
            'body' => $request->input('body'),
            'status' => $request->input('status'),
            'summary' => $request->input('summary'),
            'provider' => $request->input('provider'),
            'provider_id' => $request->input('provider_id'),
            'user_id' => auth()->id(),
            'category_id' => $request->input('category_id'),
            'published_at' => $published_at,
        ]);

        if ($request->input('media_id') !== "0") {
            $media = $this->mediaRepository->getById($request->input('media_id'));
            $media->update([
                'mediatable_type'   => $this->repository->model(),
                'mediatable_id'     => $tutorial->id
            ]);
        }

        smilify('success', "Le tutoriel a été enregistré avec succès");

        return redirect()->route('admin.tutorials.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Tutorial  $tutorial
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Tutorial $tutorial)
    {
        $categories = Category::pluck('name', 'id');
        $status = collect([
            ['value' => Tutorial::STATUS_DRAFT, 'name' => 'Brouillon'],
            ['value' => Tutorial::STATUS_PUBLISHED, 'name' => 'Publié']
        ])->pluck('name', 'value');

        return view('tutorial::tutorials.edit', compact('tutorial', 'categories', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  TutorialRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TutorialRequest $request, $id)
    {
        $published_at = now();

        if ($request->input('date')) {
            $published_at = Carbon::createFromFormat('Y-m-d H:i', $request->input('date').' '.($request->input('time') ?? now()->format('H:i')))->toDateTimeString();
        }

        $tutorial = $this->repository->updateById($id, [
            'title' => $request->input('title'),
            'body' => $request->input('body'),
            'status' => $request->input('status'),
            'summary' => $request->input('summary'),
            'provider' => $request->input('provider'),
            'provider_id' => $request->input('provider_id'),
            'category_id' => $request->input('category_id'),
            'published_at' => $published_at,
        ]);

        if ($request->input('media_id') !== "0") {

            // Get the current Media
            $media = $this->mediaRepository->getById($request->input('media_id'));

            if ($tutorial->previewImage && $tutorial->previewImage->id !== (int) $request->input('media_id')) {
                // Remove media from the given collection
                $tutorial->previewImage()->delete();

                $media->update([
                    'mediatable_type'   => $this->repository->model(),
                    'mediatable_id'     => $tutorial->id,
                ]);
            }

            $media->update([
                'mediatable_type'   => $this->repository->model(),
                'mediatable_id'     => $tutorial->id,
            ]);
        }

        smilify('success', "Le tutoriel a été modifié avec succès!");

        return redirect()->route('admin.tutorials.index');
    }

    /**
     * Supprimer un tutoriel de la base de données.
     *
     * @param  Request  $request
     * @param  Tutorial  $tutorial
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Request $request, Tutorial $tutorial)
    {
        try {
            $tutorial->delete();

            smilify('success', "Le tutoriel a été supprimé avec succès");

            if ($request->isXmlHttpRequest()) {
                return response()->json(['redirect_url' => route('admin.tutorials.index')]);
            }

            return redirect()->route('admin.tutorials.index');
        } catch (\Exception $e) {
            smilify('error', "Vous ne pouvez pas supprimer ce tutoriel!");

            return back();
        }
    }
}

Modules/Tutorial/Http/Controllers/Frontend/TutorialController.php
<?php

namespace Modules\Tutorial\Http\Controllers\Frontend;

use Illuminate\Routing\Controller;
use Inertia\Inertia;
use Modules\Tutorial\Entities\Category;
use Modules\Tutorial\Entities\Tutorial;
use Modules\Tutorial\Repositories\TutorialRepository;

class TutorialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Inertia\Response
     */
    public function index()
    {
        $tutorials = (new TutorialRepository())
            ->orderBy('published_at', 'desc')
            ->publish()
            ->paginate(16);

        return Inertia::render('tutorials/Index', [
            'tutorials' => $tutorials
        ]);
    }

    /**
     * Display a category listing posts.
     *
     * @param  string $slug
     * @return \Inertia\Response
     */
    public function category(string $slug)
    {
        $category = Category::with('tutorials')->where('slug', $slug)->firstOrFail();
        $tutorials = $category->tutorials()
            ->publish()
            ->orderBy('created_at', 'desc')
            ->paginate(16);

        return Inertia::render('tutorials/Category', [
            'category' => $category,
            'tutorials' => $tutorials
        ]);
    }

    /**
     * Display a single tutorial
     *
     * @param  string $slug
     * @return \Inertia\Response
     */
    public function show(string $slug)
    {
        $tutorial = Tutorial::where('slug', $slug)->firstOrFail();

        $tutorial->increment('visits');

        return Inertia::render('tutorials/Show', [
            'tutorial' => $tutorial
        ]);
    }
}

Modules/Tutorial/Resources/views/tutorials/create.blade.php
@extends('layouts.master')
@section('title', "Créer un nouveau tutoriel")

@section('content')

    @component('components.breadcrumb')
        <a href="{{ route('admin.tutorials.index') }}" class="text-gray-500 hover:text-gray-700 focus:outline-none focus:underline transition duration-150 ease-in-out">Tous les articles</a>
    @endcomponent

    <div class="mt-2 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
                {{ __('Créer un tutoriel') }}
            </h2>
        </div>
    </div>

    <div class="py-8">
        {!! Form::open(['route' => 'admin.tutorials.store', 'files' => true]) !!}
            <div class="flex flex-col lg:flex-row">
                <div class="w-full lg:w-2/3 space-y-5">
                    <div class="bg-white shadow rounded-md overflow-hidden px-4 py-4 sm:px-6">
                        <div class="grid grid-cols-2 gap-4">
                            <div class="col-span-2">
                                <label for="title" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Titre') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('title', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'title',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. Comment utiliser la classe Request,..."
                                        ])
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="category_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Categorie') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('category_id', $categories, null, ['class' => 'form-select block w-full', 'id' => 'category_id']); !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Status') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('status', $status, null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'status'
                                        ]);
                                    !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white shadow rounded-md overflow-hidden p-4">
                        <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __("Contenu du tutoriel") }}</label>
                        <div id="editor" class="mt-2"></div>
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Informations Optionnelles') }}</h4>
                        <div class="w-full mb-3">
                            <label for="summary" class="block text-sm font-medium leading-5 text-gray-700">Résumé du tutoriel</label>
                            <div class="mt-1 rounded-md shadow-sm">
                                {!! Form::textarea('summary', null, [
                                        'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                        'id' => 'summary',
                                        'autocomplete' => 'off',
                                        'rows' => 4,
                                    ])
                                !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="w-full lg:w-1/3 space-y-5 mt-4 lg:mt-0 lg:ml-4">
                    <div class="shadow bg-white p-4 rounded-md">
                        <h4 class="text-gray-500 font-medium text-base">{{ __('Provider') }}</h4>
                        <p class="text-gray-400 text-sm mt-2">{{ __("Le provider ici c'est le service utilisé pour la video, par default YouTube") }}</p>
                        <div class="grid grid-cols-2 gap-4 mt-6">
                            <div class="col-span-2">
                                <label for="provider" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Nom du provider') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('provider', ['youtube' => 'Youtube'], null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'provider'
                                        ]);
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-2">
                                <label for="provider_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('ID de la video') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('provider_id', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'provider_id',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. XHjdgIO(0",
                                            'required' => true
                                        ])
                                    !!}
                                </div>
                                <p class="mt-2 text-xs text-gray-500 leading-5">
                                    {{ __("L'id de la vidéo peut s'obtenir comme ceci.") }}
                                    <code class="p-1 bg-red-50 text-red-400 rounded">https://youtube.com/watch?v={<span class="text-red-600 font-medium">YOUTUBE_VIDEO_ID</span>}</code>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="shadow rounded-md">
                        <div class="bg-white p-4">
                            <h4 class="text-gray-500 font-medium text-base">{{ __('Date de publication') }}</h4>
                            <p class="text-gray-400 text-sm mt-2">{{ __('Spécifiez la date de publication de l\'article. Si aucune date n\'est renseigné la date du jour sera prise.') }}</p>
                        </div>
                        @include('components.datetime-picker', ['show' => false, 'publishedAt' => null])
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Article Preview') }}</h4>
                        <div id="dropzone-simple"></div>
                    </div>
                </div>
            </div>
            <div class="mt-8 border-t pt-5 border-gray-200">
                <div class="flex justify-end">
                    <button type="submit" class="btn btn-primary">{{ __('Enrégistrer') }}</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

Modules/Tutorial/Resources/views/tutorials/edit.blade.php
@extends('layouts.master')
@section('title', $tutorial->title)

@section('content')

    @component('components.breadcrumb')
        <a href="{{ route('admin.tutorials.index') }}" class="text-gray-500 hover:text-gray-700 focus:outline-none focus:underline transition duration-150 ease-in-out">{{ __("Tous les tutoriels") }}</a>
    @endcomponent

    <div class="mt-2 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
                {{ $tutorial->title }}
            </h2>
        </div>
    </div>

    <div class="py-8">
        {!! Form::model($tutorial, ['route' => ['admin.tutorials.update', $tutorial], 'files' => true, 'method' => 'PUT']) !!}
            <div class="flex flex-col lg:flex-row">
                <div class="w-full lg:w-2/3 space-y-5">
                    <div class="bg-white shadow rounded-md overflow-hidden">
                        @include('components.alert')
                        <div class="grid grid-cols-2 gap-4 px-4 py-4 sm:px-6">
                            <div class="col-span-2">
                                <label for="title" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Titre') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('title', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'title',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. Nouveautés de Laravel 7"
                                        ])
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="category_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Categorie') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('category_id', $categories, null, ['class' => 'form-select block w-full', 'id' => 'category_id']); !!}
                                </div>
                            </div>
                            <div class="col-span-1">
                                <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Status') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('status', $status, null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'status'
                                        ]);
                                    !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white shadow rounded-md overflow-hidden p-4">
                        <label for="status" class="block text-sm font-medium leading-5 text-gray-700">{{ __("Contenu du tutoriel") }}</label>
                        <div id="editor" class="mt-2" data-content="{{ $tutorial->body }}"></div>
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Informations Optionnelles') }}</h4>
                        <div class="w-full mb-3">
                            <label for="summary" class="block text-sm font-medium leading-5 text-gray-700">Résumé du tutoriel</label>
                            <div class="mt-1 rounded-md shadow-sm">
                                {!! Form::textarea('summary', null, [
                                        'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                        'id' => 'summary',
                                        'autocomplete' => 'off',
                                        'rows' => 4,
                                    ])
                                !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="w-full lg:w-1/3 space-y-5 mt-4 lg:mt-0 lg:ml-4">
                    <div class="shadow bg-white p-4 rounded-md">
                        <h4 class="text-gray-500 font-medium text-base">{{ __('Provider') }}</h4>
                        <p class="text-gray-400 text-sm mt-2">{{ __("Le provider ici c'est le service utilisé pour la video, par default YouTube") }}</p>
                        <div class="grid grid-cols-2 gap-4 mt-6">
                            <div class="col-span-2">
                                <label for="provider" class="block text-sm font-medium leading-5 text-gray-700">{{ __('Nom du provider') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::select('provider', ['youtube' => 'Youtube'], null, [
                                            'class' => 'form-select block w-full',
                                            'id' => 'provider'
                                        ]);
                                    !!}
                                </div>
                            </div>
                            <div class="col-span-2">
                                <label for="provider_id" class="block text-sm font-medium leading-5 text-gray-700">{{ __('ID de la video') }}</label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    {!! Form::text('provider_id', null, [
                                            'class' => "form-input block w-full sm:text-sm sm:leading-5",
                                            'id' => 'provider_id',
                                            'autocomplete' => 'off',
                                            'placeholder' => "Ex. XHjdgIO(0",
                                            'required' => true
                                        ])
                                    !!}
                                </div>
                                <p class="mt-2 text-xs text-gray-500 leading-5">
                                    {{ __("L'id de la vidéo peut s'obtenir comme ceci.") }}
                                    <code class="p-1 bg-red-50 text-red-400 rounded">https://youtube.com/watch?v={<span class="text-red-600 font-medium">YOUTUBE_VIDEO_ID</span>}</code>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="shadow rounded-md">
                        <div class="bg-white p-4">
                            <h4 class="text-gray-500 font-medium text-base">{{ __('Date de publication') }}</h4>
                            <p class="text-gray-400 text-sm mt-2">{{ __('Spécifiez la date de publication du tutoriel. Si aucune date n\'est renseigné la date du jour sera prise.') }}</p>
                        </div>
                        @include('components.datetime-picker', ['show' => true, 'publishedAt' => $tutorial->published_at])
                    </div>
                    <div class="bg-white p-4 shadow rounded-md">
                        <h4 class="text-gray-500 font-medium pb-8 text-base">{{ __('Article Preview') }}</h4>
                        <div id="dropzone-simple" data-preview="{{ $tutorial->preview_image_link }}" data-id="{{ $tutorial->preview_image_id }}"></div>
                    </div>
                </div>
            </div>
            <div class="mt-8 border-t pt-5 border-gray-200">
                <div class="flex justify-end">
                    <button type="submit" class="btn btn-primary">{{ __('Enrégistrer') }}</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
@endsection

Modules/Tutorial/Resources/views/tutorials/index.blade.php
@extends('layouts.master')
@section('title', "Listing des tutoriels")

@section('content')

    <div class="md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
            <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">{{ __('Tutoriels') }}</h2>
        </div>
        <div class="mt-4 flex md:mt-0 md:ml-4">
            <span class="shadow-sm rounded-md">
              <a href="{{ route('admin.tutorials.create') }}" class="btn btn-primary inline-flex items-center transition duration-150 ease-in-out">
                {{ __('Ajouter un tutoriel') }}
              </a>
            </span>
        </div>
    </div>

    @livewire('tutorial-list')

@endsection